Repository RisingSunLight42/TD2_TRAVaie_PtiCuisto, pull requests merged in 2023-10, with the labels that each got.

#20 ✅ ADD pages and arborescence, and folders
  assets/css/style.css
  assets/fonts/void.txt
  assets/images/Logo.png
  assets/images/Pticuisto.png
  assets/images/void.txt
  index.php
  templates/all_recipes.php
  templates/filter.php
  templates/list.php
  templates/recipe.php
Labels: enhancement, php, HTML

#23 📝 Add readme
  README.md
Labels: documentation, enhancement

#25 Add GitHub templates
  .github/ISSUE_TEMPLATE/addition.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#27 Connexion creation
  .gitignore
  index.php
  templates/connexion.example
Labels: enhancement, php

#28 fix connexion.exemple
  templates/connexion.example
Labels: enhancement, php

#30 Add .env file
  .env.template
  .gitignore
  assets/php/connexion.php
  templates/connexion.example
Labels: documentation, enhancement, database
